# Generated by Django 4.1.7 on 2023-04-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('posted_date', models.DateTimeField()),
                ('productivity', models.IntegerField()),
            ],
        ),
    ]
